services:
  # BookIt API Web Service
  - type: web
    name: bookit-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookit-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: PYTHON_VERSION
        value: 3.11.4

  # PostgreSQL Database
  - type: pserv
    name: bookit-db
    env: postgresql
    plan: starter
    ipAllowList: []