services:
  # PostgreSQL Database
  - type: pserv
    name: bookit-db
    env: postgresql
    plan: free
    databaseName: bookit_db
    user: bookit_user
    ipAllowList: []

  # BookIt API Web Service  
  - type: web
    name: bookit-api
    runtime: docker
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookit-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30