services:
  # BookIt API Web Service
  - type: web
    name: bookit-api
    runtime: docker
    plan: free
    repo: https://github.com/rhoseck/Bookit.git
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookit-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30

  # PostgreSQL Database
  - type: pserv
    name: bookit-db
    plan: free
    databaseName: bookit_db
    user: bookit_user