"""remove public_id column

Revision ID: 2367c6ec594f
Revises: c674faefa019
Create Date: 2025-10-01 18:46:32.491217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2367c6ec594f'
down_revision: Union[str, Sequence[str], None] = 'c674faefa019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('name', sa.String(), nullable=True))
    op.alter_column('services', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_column('services', 'title')
    op.drop_column('services', 'duration_minutes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('services', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('services', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_column('services', 'name')
    # ### end Alembic commands ###
