"""add start_time and end_time to booking

Revision ID: a2861dcef4d6
Revises: a7b705b8f837
Create Date: 2025-09-28 00:38:27.892173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2861dcef4d6'
down_revision: Union[str, Sequence[str], None] = 'a7b705b8f837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('bookings', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.drop_constraint(op.f('bookings_book_id_fkey'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'book_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('bookings_book_id_fkey'), 'bookings', 'books', ['book_id'], ['id'])
    op.drop_column('bookings', 'end_time')
    op.drop_column('bookings', 'start_time')
    # ### end Alembic commands ###
