"""complete service

Revision ID: a6563a8da2d3
Revises: a2861dcef4d6
Create Date: 2025-09-28 00:59:42.484307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6563a8da2d3'
down_revision: Union[str, Sequence[str], None] = 'a2861dcef4d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('title', sa.String(), nullable=False))
    op.add_column('services', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('duration_minutes', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('services', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('services', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('services', 'created_at')
    op.drop_column('services', 'is_active')
    op.drop_column('services', 'duration_minutes')
    op.drop_column('services', 'price')
    op.drop_column('services', 'title')
    # ### end Alembic commands ###
